### PR TITLE
Fix headers

### PR DESCRIPTION
**Pull request by aruke**

### CODE REVIEW

**Comment by joejune** [comment]
Looks great, thanks!

I'm curious, what do you use Bluetility for?

**Comment by jnross** [comment]
Looks great, thanks!

I'm curious, what do you use Bluetility for?

**Comment by aruke** [comment]
I am looking for a tool with which I can host a GattServer on my Mac and then make the android GattDevice to connect to it. It seems Blutility doesn't have that functionality yet. Can it be added?

**Comment by joejune** [comment]
It would certainly be possible to add such a feature.  However, I don't have a need for such a feature at this time and don't have any plans to build it.  You're welcome to add an issue for this, and if you want to write the feature, I will consider a PR.

**Comment by jnross** [comment]
It would certainly be possible to add such a feature. However, I don't have a need for such a feature at this time and don't have any plans to build it. You're welcome to add an issue for this, and if you want to write the feature, I will consider a PR.

**Comment by aruke** [comment]
👍🏻

**Pull request merged**
